import { Contact } from "../../shared/types";

export const contacts: Omit<Contact, "contactId">[] = [
  {
    firstName: "Agata",
    lastName: "Waliłko",
    phone: "",
    email: "",
  },
  {
    firstName: "Agnieszka",
    lastName: "Miśko",
    phone: "660243847",
    email: "",
  },
  {
    firstName: "Anna",
    lastName: "Szweda",
    phone: "507016159",
    email: "annaszweda1@wp.pl",
  },
  {
    firstName: "Aleksandra",
    lastName: "Fronckiewicz",
    phone: "507893107",
    email: "aleksandrafronckiewicz@spcychry.pl",
  },
  {
    firstName: "Alicja",
    lastName: "Mielimiączka",
    phone: "509054073",
    email: "",
  },
  {
    firstName: "Alina",
    lastName: "Gołuchowska",
    phone: "607825562",
    email: "alina-goluchowska@wp.pl",
  },
  {
    firstName: "Anna",
    lastName: "Azarkiewicz",
    phone: "600805282",
    email: "",
  },
  {
    firstName: "Anna",
    lastName: "Kowalczyk",
    phone: "571343570",
    email: "lopik26@wp.pl",
  },
  {
    firstName: "Anna",
    lastName: "Michalska",
    phone: "",
    email: "anna.michalska@zpokarsko.pl",
  },
  {
    firstName: "Barbara",
    lastName: "Tomaszewska",
    phone: "693435017",
    email: "bar_tom@interia.pl",
  },
  {
    firstName: "Barbara",
    lastName: "Świątek",
    phone: "503353080",
    email: "superbasik@tlen.pl",
  },
  {
    firstName: "Dorota",
    lastName: "Sytek",
    phone: "695744153",
    email: "",
  },
  {
    firstName: "Dariusz",
    lastName: "Matwijów",
    phone: "511092139",
    email: "daro88885@wp.pl",
  },
  {
    firstName: "Dominika Daniel",
    lastName: "Kosiorek",
    phone: "",
    email: "dominikaboczek@wp.pl",
  },
  {
    firstName: "Dorota",
    lastName: "Deja",
    phone: "",
    email: "",
  },
  {
    firstName: "Edyta",
    lastName: "Hadryś",
    phone: "792151085",
    email: "ejdif@tlen.pl",
  },
  {
    firstName: "Iwona",
    lastName: "Śmierska",
    phone: "666377465",
    email: "smierska@sp2mysliborz.pl",
  },
  {
    firstName: "Ewa",
    lastName: "Galicka",
    phone: "505110047",
    email: "",
  },
  {
    firstName: "Iwona",
    lastName: "Kucharska",
    phone: "508462919",
    email: "",
  },
  {
    firstName: "Iwona",
    lastName: "Kucharska",
    phone: "508462919",
    email: "ivonka63@wp.pl",
  },
  {
    firstName: "Iwona",
    lastName: "Olobry",
    phone: "734199660",
    email: "iva.biol@onet.eu",
  },
  {
    firstName: "Iwona",
    lastName: "Stasiak",
    phone: "",
    email: "szkoły",
  },
  {
    firstName: "Joanna",
    lastName: "Lipka",
    phone: "661156602",
    email: "joannalipka102@o2.pl",
  },
  {
    firstName: "Joanna",
    lastName: "Prochorenko",
    phone: "781145275",
    email: "j.prochorenko89@gmail.com",
  },
  {
    firstName: "Joanna",
    lastName: "Przepiórka",
    phone: "509316591",
    email: "a.przepiorka3@wp.pl",
  },
  {
    firstName: "Joanna",
    lastName: "Przepiórka",
    phone: "509316591",
    email: "a.przepiorka3@wp.pl",
  },
  {
    firstName: "Karolina",
    lastName: "Kwiatkowska",
    phone: "661484970",
    email: "kpkwiatkowscy@wp.pl",
  },
  {
    firstName: "Julita",
    lastName: "Witkowska",
    phone: "510924070",
    email: "",
  },
  {
    firstName: "Justyna",
    lastName: "Kozłowska",
    phone: "504631902",
    email: "justyna.kozlowska@interia.pl",
  },
  {
    firstName: "Justyna",
    lastName: "Ryszawa",
    phone: "737524697",
    email: "ryszawa@sp2mysliborz.pl",
  },
  {
    firstName: "Katarzyna",
    lastName: "Gołębiowska",
    phone: "723911601",
    email: "katarzyna.golembiowska@sprozansko.pl",
  },
  {
    firstName: "Karolina",
    lastName: "Stoparek",
    phone: "",
    email: "karolka448@wp.pl",
  },
  {
    firstName: "Karolina",
    lastName: "Tomiałojć",
    phone: "783860422",
    email: "",
  },
  {
    firstName: "Katarzyna",
    lastName: "Maksymiuk",
    phone: "607502298",
    email: "katarzyna.maksymiuk01@gmail.com",
  },
  {
    firstName: "Lidia",
    lastName: "Gręda",
    phone: "607406574",
    email: "lidia110@wp.pl",
  },
  {
    firstName: "Magdalena",
    lastName: "Remian-Wieczorek",
    phone: "",
    email: "magda.remian@gmail.com",
  },
  {
    firstName: "Magdalena",
    lastName: "Horla",
    phone: "603237093",
    email: "horla@ohp.pl",
  },
  {
    firstName: "Magdalena",
    lastName: "Moszkowska",
    phone: "",
    email: "moszkowskam@o2.pl",
  },
  {
    firstName: "Małgorzata",
    lastName: "Jabłońska",
    phone: "606419343",
    email: "jablonskam@sp4barlinek.edupage.org",
  },
  {
    firstName: "Małgorzata",
    lastName: "Kałużna",
    phone: "600901233",
    email: "aldona.rosa@zpokarsko.pl",
  },
  {
    firstName: "Małgorzata",
    lastName: "Kuszyk",
    phone: "",
    email: "malgorzatak@sp1smolnica.pl",
  },
  {
    firstName: "Małgorzata",
    lastName: "Rutkowska",
    phone: "",
    email: "trutkowski171@wp.pl",
  },
  {
    firstName: "Marcin",
    lastName: "Churski",
    phone: "",
    email: "",
  },
  {
    firstName: "Marika",
    lastName: "Horyń-Kowalik",
    phone: "",
    email: "m.horyn-kowalik@zsnoblistow.pl",
  },
  {
    firstName: "Marta",
    lastName: "Kostowska",
    phone: "518513567",
    email: "",
  },
  {
    firstName: "Martyna",
    lastName: "Kalicka",
    phone: "605560941",
    email: "martyna8479@wp.pl",
  },
  {
    firstName: "Monika",
    lastName: "Bijak",
    phone: "",
    email: "monikabijak33@wp.pl",
  },
  {
    firstName: "Monika",
    lastName: "Franków-Śniadała",
    phone: "",
    email: "frania921@gmail.com",
  },
  {
    firstName: "Natalia Hertel/Izabela",
    lastName: "Sekuła",
    phone: "512823092",
    email: "natalia_hertel@wp.pl",
  },
  {
    firstName: "Oliwia",
    lastName: "Kicińska-Sawicka",
    phone: "",
    email: "",
  },
  {
    firstName: "Paulina",
    lastName: "Dwojewska",
    phone: "",
    email: "",
  },
  {
    firstName: "Paweł",
    lastName: "Szymczyk",
    phone: "504150457",
    email: "szymczyk@sp2mysliborz.pl",
  },
  {
    firstName: "Sylwia",
    lastName: "Antczak",
    phone: "508304345",
    email: "sylwia_antczak@onet.pl",
  },
  {
    firstName: "Sylwia",
    lastName: "Lewandowska",
    phone: "",
    email: "s.lewandowska@zsnoblistow.pl",
  },
  {
    firstName: "Zofia",
    lastName: "Cynarska",
    phone: "509606869",
    email: "",
  },
  {
    firstName: "Iwona",
    lastName: "Kuchcińska",
    phone: "",
    email: "",
  },
  {
    firstName: "Jolanta",
    lastName: "Szczepanowska",
    phone: "",
    email: "szczepanowska@sp2mysliborz.pl",
  },
  {
    firstName: "Jerzy",
    lastName: "Warachowski",
    phone: "",
    email: "",
  },
];
