import { schoolParams } from "./controllers/schoolController";

const defaultSchoolAddress: schoolParams[] = [
  {
    name: "Branżowa Szkoła I Stopnia Nr 1 w Barlinku",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "I Liceum Ogólnokształcące w Barlinku",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Niepubliczna Szkoła Podstawowa RADOSNA",
    address: "ul. Szosowa 3",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Niepubliczne Przedszkole Językowe Wiśniowym Sadzie Jolanta Maria Rybarczyk",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Klub Dziecięcy w Wiśniowym Sadzie Jolanta Maria Rybarczyk",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: 'Niepubliczne Przedszkole Specjalne "BRATEK"',
    address: "ul. Sienkiewicza 15",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Przedszkole Miejskie nr 1 Janiny Porazińskiej",
    address: "ul. Kombatantów 3",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: 'Przedszkole Miejskie nr 2 "Pod Topolą" w Barlinku',
    address: "ul. Podwale 11",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Szkoła Podstawowa nr 1 im. Tadeusza Kościuszki w Barlinku",
    address: "ul. Jeziorna 12",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Szkoła Podstawowa nr 4 im. Henryka Sienkiewicza w Barlinku",
    address: "ul. Kombatantów 3",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Szkoła Policealna dla dorosłych w Barlinku",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Szkoła Przysposabiająca do Pracy",
    address: "ul. Sienkiewicza 15",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Technikum nr 1 w Barlinku",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Żłobek miejski w Barlinku",
    address: "ul. Podwale 11",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Ośrodek Szkolenia i Wychowania Ochotniczych Hufców Pracy w Barlinku",
    address: "ul. Św. Bonifacego 36",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Niepubliczna Szkoła Podstawowa w Barnówku",
    address: "Barnówko",
    city: "Barnówko",
    postalCode: "74-311",
    municipality: "Myślibórz",
  },
  {
    name: "Niepubliczne Małe Przedszkole w Barnówku",
    address: "Barnówko",
    city: "Barnówko",
    postalCode: "74-311",
    municipality: "Myślibórz",
  },
  {
    name: "Przedszkole Gminne w Boleszkowicach",
    address: "ul. Słoneczna 24a",
    city: "Boleszkowice",
    postalCode: "74-407",
    municipality: "Dębno",
  },
  {
    name: "Szkoła Podstawowa im. Bolesława Chrobrego w Boleszkowicach",
    address: "Pl. Bolesława Chrobrego 3",
    city: "Boleszkowice",
    postalCode: "74-407",
    municipality: "Dębno",
  },
];
