import { CreateSchoolWithInstitutionDto } from "../../shared/types/index";

const educationalInstitutions: CreateSchoolWithInstitutionDto[] = [
  {
    name: "Branżowa Szkoła I Stopnia Nr 1 w Barlinku",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "I Liceum Ogólnokształcące w Barlinku",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Niepubliczna Szkoła Podstawowa RADOSNA",
    address: "ul. Szosowa 3",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Niepubliczne Przedszkole Językowe Wiśniowym Sadzie Jolanta Maria Rybarczyk",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Klub Dziecięcy w Wiśniowym Sadzie Jolanta Maria Rybarczyk",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Niepubliczne Przedszkole Specjalne 'BRATEK'",
    address: "ul. Sienkiewicza 15",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Przedszkole Miejskie nr 1 Janiny Porazińskiej",
    address: "ul. Kombatantów 3",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Przedszkole Miejskie nr 2 'Pod Topolą' w Barlinku",
    address: "ul. Podwale 11",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Szkoła Podstawowa nr 1 im. Tadeusza Kościuszki w Barlinku",
    address: "ul. Jeziorna 12",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Szkoła Podstawowa nr 4 im. Henryka Sienkiewicza w Barlinku",
    address: "ul. Kombatantów 3",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Szkoła Policealna dla dorosłych w Barlinku",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Szkoła Przysposabiająca do Pracy",
    address: "ul. Sienkiewicza 15",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Technikum nr 1 w Barlinku",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Żłobek miejski w Barlinku",
    address: "ul. Podwale 11",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Ośrodek Szkolenia i Wychowania Ochotniczych Hufców Pracy w Barlinku",
    address: "ul. Św. Bonifacego 36",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
  },
  {
    name: "Niepubliczna Szkoła Podstawowa w Barnówku",
    address: "Barnówko",
    city: "Barnówko",
    postalCode: "74-311",
    municipality: "Różańsko",
  },
  {
    name: "Niepubliczne Małe Przedszkole w Barnówku",
    address: "Barnówko",
    city: "Barnówko",
    postalCode: "74-311",
    municipality: "Różańsko",
  },
  {
    name: "Przedszkole Gminne w Boleszkowicach",
    address: "ul. Słoneczna 24a",
    city: "Boleszkowice",
    postalCode: "74-407",
    municipality: "Boleszkowice",
  },
  {
    name: "Szkoła Podstawowa im. Bolesława Chrobrego w Boleszkowicach",
    address: "Pl. Bolesława Chrobrego 3 oraz ul. Słoneczna 24 (IV-VIII)",
    city: "Boleszkowice",
    postalCode: "74-407",
    municipality: "Boleszkowice",
  },
  {
    name: "Punkt Przedszkolny 'Puchatek' w Cychrach",
    address: "ul. Jana Pawła II 66/5",
    city: "Cychry",
    postalCode: "74-404",
    municipality: "Cychry",
  },
  {
    name: "Szkoła Podstawowa im. Marii Konopnickiej w Sarbinowie",
    address: "Sarbinowo 80",
    city: "Sarbinowo",
    postalCode: "74-404",
    municipality: "Cychry",
  },
  {
    name: "Szkoła Podstawowa im. Władysława St. Reymonta w Cychrach",
    address: "ul. Jana Pawła II 85",
    city: "Cychry",
    postalCode: "74-404",
    municipality: "Cychry",
  },
  {
    name: "Niepubliczne Przedszkole Montessori z oddziałami integracyjnymi i specjalnymi Żaneta Rybińska-Prostak, Joanna Kujawa S.C.",
    address: "", // Address not provided in original data
    city: "", // City not provided in original data
    postalCode: "", // Postal code not provided in original data
    municipality: "", // Municipality not provided in original data
  },
  {
    name: "Branżowa Szkoła I Stopnia w Dębnie",
    address: "ul. Zachodnia 4",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
  },
  {
    name: "I Liceum Ogólnokształcące w Dębnie",
    address: "ul. Zachodnia 4",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
  },
  {
    name: "Niepubliczna Szkoła Podstawowa w Dębnie",
    address: "ul. Baczewskiego 20",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
  },
  {
    name: "Niepubliczne Liceum Ogólnokształcące",
    address: "ul. Baczewskiego 20",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
  },
  {
    name: "Przedszkole Specjalnego Towarzystwa Salezjańskiego im. Św. Jana Bosko",
    address: "ul. Mickiewicza 33",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
  },
  {
    name: "Niepubliczne Przedszkole Towarzystwa Salezjańskiego im. Św. Jana Bosko",
    address: "Plac Konstytucji 3 Maja 2",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
  },
  {
    name: "Przedszkole nr 1 Czarodziejska Kraina w Dębnie",
    address: "ul. Kościuszki 6",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
  },
  {
    name: "Przedszkole nr 2 im. Stanisławy Modrzejewskiej w Dębnie",
    address: "ul. Jana Pawła II 42",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
  },
  {
    name: "Szkoła Podstawowa nr 1 im. KEN w Dębnie",
    address: "ul. Marszałka J. Piłsudskiego 10",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
  },
  {
    name: "Szkoła Podstawowa nr 2 im. Arkadego Fiedlera w Dębnie",
    address: "ul. Jana Pawła II 1",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
  },
  {
    name: "Szkoła Podstawowa nr 3 im. J. Dąbrowskiego",
    address: "ul. J. Słowackiego 21",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
  },
  {
    name: "Szkoła Podstawowa Towarzystwa Salezjańskiego im. św. Jana Bosko w Dębnie",
    address: "ul. Mickiewicza 33",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
  },
  {
    name: "Szkoła Policealna dla Dorosłych w Dębnie",
    address: "ul. Zachodnia",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
  },
  {
    name: "Żłobek Gminny w Dębnie",
    address: "ul. Jana Pawła II 42",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
  },
  {
    name: "Szkoła Podstawowa im. Adama Mickiewicza w Golenicach",
    address: "Golenice 1a",
    city: "Golenice",
    postalCode: "74-300",
    municipality: "Myslibórz",
  },
  {
    name: "Przedszkole Gminne w Karsku",
    address: "ul. Gorzowska 9",
    city: "Karsko",
    postalCode: "74-305",
    municipality: "Karsko",
  },
  {
    name: "Szkoła Podstawowa im. H. Ch. Andersena w Karsku",
    address: "ul. Gorzowska 9",
    city: "Karsko",
    postalCode: "74-305",
    municipality: "Karsko",
  },
  {
    name: "Szkoła Podstawowa im. Janusza Korczaka w Kierzkowie",
    address: "Kierzków 69",
    city: "Kierzków",
    postalCode: "74-300",
    municipality: "Myślibórz",
  },
  {
    name: "Szkoła Podstawowa im. Jana Pawła II w Mostkowie",
    address: "74-322 Mostkowo 37D",
    city: "Mostkowo",
    postalCode: "74-322",
    municipality: "Mostkowo",
  },
  {
    name: "Branżowa Szkoła I Stopnia Nr 2 w Myśliborzu",
    address: "ul. Strzelecka 51",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
  },
  {
    name: "Liceum Ogólnokształcące im. Noblistów Polskich",
    address: "ul. Za bramką 8",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
  },
  {
    name: "Młodzieżowy Ośrodek Socjoterapi w Myśliborzu",
    address: "ul. Marcinkowskiego 10",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
  },
  {
    name: "Niepubliczne Przedszkole im. Żwirka i Muchomorka",
    address: "ul. Armii Polskiej 13",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
  },
  {
    name: "Oddział I Żłobka Miejskiego w Myśliborzu",
    address: "ul. Spokojna 22",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
  },
  {
    name: "Przedszkole Publiczne Nr 1 'Zielona Dolinka' w Myśliborzu",
    address: "ul. Lipowa 18b", // Address not provided in original data
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
  },
  {
    name: "Przedszkole Publiczne nr 2 Misia Uszatka",
    address: "ul. Spokojna 12",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
  },
  {
    name: "Specjalny Ośrodek Szkolno-Wychowawczy TPD w Myśliborzu",
    address: "ul. Pileckiego 27/Spokojna 22",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
  },
  {
    name: "Szkoła Podstawowa nr 2 im. Janusza Kusocińskiego w Myśliborzu",
    address: "ul. Piłsudskiego 18",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
  },
  {
    name: "Szkoła Podstawowa nr 3 im. Leonida Teligi w Myśliborzu",
    address: "ul. Lipowa 18a",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
  },
  {
    name: "Szkoła Policealna w Myśliborzu",
    address: "ul. Strzelecka 51",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
  },
  {
    name: "Technikum nr 1 w Myśliborzu",
    address: "ul. Strzelecka 51",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
  },
  {
    name: "Technikum nr 2 Myśliborzu",
    address: "ul. Za Bramką 8",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
  },
  {
    name: "Żłobek miejski w Myśliborzu",
    address: "ul. Spokojna 15",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
  },
  {
    name: "Szkoła Podstawowa im. Jana Brzechwy w Nawrocku",
    address: "Nawrocko 11",
    city: "Nawrocko",
    postalCode: "74-300",
    municipality: "Myślibórz",
  },
  {
    name: "Szkoła Podstawowa im. Unii Europejskiej",
    address: "ul. Szkolna 4",
    city: "Nowogródek Pomorski",
    postalCode: "74-304",
    municipality: "Nowogródek Pomorski",
  },
  {
    name: "Szkoła Podstawowa im. Kornela Makuszyńskiego w Różańsku",
    address: "74-311 Różańsko 87",
    city: "Różańsko",
    postalCode: "74-311",
    municipality: "Różańsko",
  },
  {
    name: "Niepubliczne Przedszkole 'Małe Przedszkole' w Rychnowie",
    address: "", // Address not provided in original data
    city: "Rychnowo",
    postalCode: "", // Postal code not provided in original data
    municipality: "", // Municipality not provided in original data
  },
  {
    name: "Młodzieżowy Ośrodek Socjoterapi w Smolnica",
    address: "Smolnica 51",
    city: "Smolnica",
    postalCode: "74-400",
    municipality: "Dębno",
  },
  {
    name: "Szkoła Podstawowa nr 1 im. Młodych Talentów w Smolnicy",
    address: "Smolnica 21",
    city: "Smolnica",
    postalCode: "74-400",
    municipality: "Dębno",
  },
];
