import { Program } from "../../shared/types";

export const programs: Omit<Program, "programId">[] = [
  { referenceNumber: "966.1", name: "Trzymaj formę", programType: "programowy", description: "" },
  { referenceNumber: "966.2", name: "HIV/AIDS", programType: "programowy", description: "" },
  { referenceNumber: "966.2", name: "Ars - czyli jak dbać o miłość", programType: "programowy", description: "" },
  { referenceNumber: "966.2", name: "Światowy Dzień AIDS", programType: "programowy", description: "" },
  {
    referenceNumber: "966.3",
    name: "Zdrowe zęby mamy, marchewkę zajadamy",
    programType: "programowy",
    description: "",
  },
  { referenceNumber: "966.4", name: "Higiena naszą tarczą ochronną", programType: "programowy", description: "" },
  {
    referenceNumber: "966.5",
    name: "Porozmawiajmy o zdrowiu i nowych zagrożeniach",
    programType: "programowy",
    description: "",
  },
  {
    referenceNumber: "966.6",
    name: "Profilaktyka używania napojów energetycznych",
    programType: "nieprogramowy",
    description: "",
  },
  { referenceNumber: "966.6", name: "Profilaktyka palenia tytoniu", programType: "nieprogramowy", description: "" },
  { referenceNumber: "966.6", name: "Światowy Dzień Rzucania Palenia", programType: "nieprogramowy", description: "" },
  { referenceNumber: "966.6", name: "Nowe narkotyki", programType: "nieprogramowy", description: "" },
  {
    referenceNumber: "966.7",
    name: "Promocja zdrowego stylu życia - inne",
    programType: "nieprogramowy",
    description: "",
  },
  { referenceNumber: "966.7", name: "Promocja zdrowego stylu życia", programType: "nieprogramowy", description: "" },
  {
    referenceNumber: "966.7",
    name: "Skąd się biorą ekologiczne produkty",
    programType: "nieprogramowy",
    description: "",
  },
  { referenceNumber: "966.7", name: "Profilaktyka cukrzycy", programType: "nieprogramowy", description: "" },
  { referenceNumber: "966.7", name: "Kampania EFSA", programType: "nieprogramowy", description: "" },
  { referenceNumber: "966.7", name: "Bieg po zdrowie", programType: "nieprogramowy", description: "" },
  { referenceNumber: "966.8", name: "Podstępne WZW", programType: "nieprogramowy", description: "" },
  {
    referenceNumber: "966.8",
    name: "Profilaktyka chorób odkleszczowych",
    programType: "nieprogramowy",
    description: "",
  },
  { referenceNumber: "966.8", name: "Profilaktyka grypy", programType: "nieprogramowy", description: "" },
  { referenceNumber: "966.9", name: "Znamię, znam je", programType: "nieprogramowy", description: "" },
  {
    referenceNumber: "966.9",
    name: "Profilaktyka nowotworowa - Profilaktyka raka piersi",
    programType: "nieprogramowy",
    description: "",
  },
  { referenceNumber: "966.9", name: "Profilaktyka nowotworowa", programType: "nieprogramowy", description: "" },
  {
    referenceNumber: "966.9",
    name: "Profilaktyka nowotworowa - Profilaktyka raka jąder",
    programType: "nieprogramowy",
    description: "",
  },
  { referenceNumber: "966.11", name: "Promocja szczepień ochronnych", programType: "nieprogramowy", description: "" },
  { referenceNumber: "966.11", name: "Europejski Tydzień Szczepień", programType: "nieprogramowy", description: "" },
  { referenceNumber: "966.12", name: "Światowy Dzień Zdrowia", programType: "nieprogramowy", description: "" },
  { referenceNumber: "966.14", name: "Bezpieczne ferie", programType: "nieprogramowy", description: "" },
  { referenceNumber: "966.14", name: "Bezpieczne Wakacje", programType: "nieprogramowy", description: "" },
  { referenceNumber: "966.16", name: "Cyberprzemoc", programType: "nieprogramowy", description: "" },
  { referenceNumber: "966.17", name: "Radon", programType: "nieprogramowy", description: "" },
  { referenceNumber: "966.17", name: "Czyste powietrze wokół nas", programType: "nieprogramowy", description: "" },
  { referenceNumber: "966.17", name: "Światowy Dzień Wody", programType: "nieprogramowy", description: "" },
  { referenceNumber: "966.18", name: "Moja szkoła, zdrowa szkoła", programType: "nieprogramowy", description: "" },
  { referenceNumber: "966.18", name: "Profilaktyka wad postawy", programType: "nieprogramowy", description: "" },
  { referenceNumber: "966.19", name: "Power Ukraina", programType: "nieprogramowy", description: "" },
];
